import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Bell, Mail, MessageCircle, Plus, Send, ShieldCheck, UsersRound } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

const fieldClass = "h-11 w-full rounded-xl border border-[#cfddd6] bg-[#fbfcf9] px-3.5 text-sm text-[#3b4d60] outline-none transition placeholder:text-[#789089] focus:border-[#76c9bc] focus:ring-2 focus:ring-[#ccebe5]";
const emptyAccess = { studentId: "", email: "", fullName: "", password: "" };
const emptyMessage = { guardianId: "", studentId: "", subject: "", body: "" };

export default function FamilyCommunication() {
  const me = trpc.auth.me.useQuery();
  const allowed = me.data?.localRole === "owner" || me.data?.localPermissions?.includes("communications");
  const utils = trpc.useUtils();
  const students = trpc.school.students.useQuery(undefined, { enabled: Boolean(allowed) });
  const accounts = trpc.school.guardianAccounts.useQuery(undefined, { enabled: Boolean(allowed) });
  const messages = trpc.school.schoolMessages.useQuery(undefined, { enabled: Boolean(allowed) });
  const [access, setAccess] = useState(emptyAccess);
  const [message, setMessage] = useState(emptyMessage);
  const createAccess = trpc.school.createGuardianAccount.useMutation({ onSuccess: async result => { setAccess(emptyAccess); await utils.school.guardianAccounts.invalidate(); toast.success(`Acesso criado para ${result.studentName}.`); }, onError: error => toast.error(error.message) });
  const send = trpc.school.sendGuardianAnnouncement.useMutation({ onSuccess: async () => { setMessage(emptyMessage); await Promise.all([utils.school.schoolMessages.invalidate(), utils.school.guardianAccounts.invalidate()]); toast.success("Mensagem enviada ao responsável."); }, onError: error => toast.error(error.message) });
  const accountOptions = useMemo(() => { const map = new Map<number, { id: number; label: string; email: string; students: Array<{ id: number; name: string }> }>(); for (const row of accounts.data ?? []) { const current = map.get(row.id) ?? { id: row.id, label: row.fullName, email: row.email, students: [] }; if (row.studentId && row.studentName && !current.students.some(student => student.id === row.studentId)) current.students.push({ id: row.studentId, name: row.studentName }); map.set(row.id, current); } return Array.from(map.values()); }, [accounts.data]);
  if (!allowed) return <Card><CardContent className="p-8 text-sm text-[#516273]">Sua função não tem permissão para acessar a comunicação com famílias.</CardContent></Card>;
  return <div className="mx-auto max-w-7xl space-y-7">
    <section className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#138378]">Comunicação escolar</p><h2 className="mt-2 font-display text-3xl font-bold text-[#12233f]">Famílias e mensagens</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#758492]">Crie o acesso individual do responsável, envie comunicados e acompanhe as mensagens recebidas pela secretaria.</p></div><Badge className="w-fit bg-[#e5f3ef] px-3 py-1.5 text-[#10766c] hover:bg-[#e5f3ef]"><ShieldCheck className="mr-1.5 h-4 w-4" /> Acesso controlado</Badge></section>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_390px]">
      <Card className="border-[#e6eae9] bg-white shadow-[0_12px_32px_rgba(26,54,73,.055)]"><CardContent className="p-5 sm:p-7"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#e7f4f1] text-[#14877e]"><UsersRound className="h-5 w-5" /></div><div><h3 className="font-bold text-[#12233f]">Acessos familiares</h3><p className="text-xs text-[#647b79]">Cada responsável deve receber suas credenciais por um canal seguro.</p></div></div><div className="mt-5 space-y-3">{accounts.isLoading ? <p className="text-sm text-[#647b79]">Carregando acessos...</p> : accountOptions.map(account => <div key={account.id} className="rounded-2xl border border-[#e8edeb] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold text-[#12233f]">{account.label}</p><p className="mt-1 text-xs text-[#647b79]">{account.email}</p></div><Badge variant="outline" className="border-[#ccece1] bg-[#eff9f4] text-[#158265]">Ativo</Badge></div><p className="mt-3 text-xs text-[#526f69]">Aluno(s): {account.students.map(student => student.name).join(", ") || "sem vínculo"}</p></div>)}{!accounts.isLoading && !accountOptions.length && <div className="rounded-2xl border border-dashed border-[#cfe0d8] bg-[#fbfdfb] p-7 text-center"><UsersRound className="mx-auto h-8 w-8 text-[#73a897]" /><p className="mt-3 text-sm font-bold text-[#33564d]">Nenhum acesso familiar ainda</p><p className="mt-1 text-xs text-[#647b79]">Crie o primeiro acesso no formulário ao lado.</p></div>}</div></CardContent></Card>
      <Card className="h-fit border-[#e6eae9] bg-[#fffefb] shadow-[0_12px_32px_rgba(26,54,73,.055)]"><CardContent className="p-5 sm:p-6"><div className="flex items-center gap-2"><Plus className="h-5 w-5 text-[#14877e]" /><h3 className="font-bold text-[#12233f]">Criar acesso familiar</h3></div><p className="mt-2 text-xs leading-5 text-[#647b79]">O e-mail precisa ser o mesmo cadastrado no responsável do aluno.</p><form className="mt-5 space-y-4" onSubmit={event => { event.preventDefault(); createAccess.mutate({ ...access, studentId: Number(access.studentId) }); }}><div className="space-y-1.5"><Label htmlFor="family-student">Aluno vinculado</Label><select id="family-student" required className={fieldClass} value={access.studentId} onChange={event => { const student = students.data?.find(item => item.id === Number(event.target.value)); setAccess({ ...access, studentId: event.target.value, email: student?.guardianEmail ?? "", fullName: student?.guardianName ?? "" }); }}><option value="">Selecione o aluno</option>{students.data?.filter(student => student.status === "active").map(student => <option key={student.id} value={student.id}>{student.name} — {student.guardianName}</option>)}</select></div><div className="space-y-1.5"><Label htmlFor="family-email">E-mail do responsável</Label><Input id="family-email" type="email" required maxLength={320} placeholder="responsavel@exemplo.com" value={access.email} onChange={event => setAccess({ ...access, email: event.target.value })} /></div><div className="space-y-1.5"><Label htmlFor="family-name">Nome do responsável</Label><Input id="family-name" required maxLength={160} value={access.fullName} onChange={event => setAccess({ ...access, fullName: event.target.value })} /></div><div className="space-y-1.5"><Label htmlFor="family-password">Senha inicial</Label><Input id="family-password" type="password" required minLength={8} maxLength={128} placeholder="Mínimo de 8 caracteres" value={access.password} onChange={event => setAccess({ ...access, password: event.target.value })} /></div><Button disabled={createAccess.isPending} className="w-full bg-[#12233f] text-white hover:bg-[#244165]">{createAccess.isPending ? "Salvando..." : "Criar acesso"}</Button></form></CardContent></Card>
    </div>
    <Card className="border-[#e6eae9] bg-white shadow-[0_12px_32px_rgba(26,54,73,.055)]"><CardContent className="p-5 sm:p-7"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#fff0df] text-[#c2772d]"><Mail className="h-5 w-5" /></div><div><h3 className="font-bold text-[#12233f]">Enviar comunicado</h3><p className="text-xs text-[#647b79]">A família receberá a mensagem no portal e uma notificação interna.</p></div></div><form className="mt-5 grid gap-4 md:grid-cols-2" onSubmit={event => { event.preventDefault(); send.mutate({ guardianId: Number(message.guardianId), studentId: message.studentId ? Number(message.studentId) : undefined, subject: message.subject, body: message.body }); }}><label className="space-y-1.5"><span className="text-xs font-bold text-[#657584]">Responsável</span><select required className={fieldClass} value={message.guardianId} onChange={event => setMessage({ ...message, guardianId: event.target.value, studentId: "" })}><option value="">Selecione o responsável</option>{accountOptions.map(account => <option key={account.id} value={account.id}>{account.label} — {account.email}</option>)}</select></label><label className="space-y-1.5"><span className="text-xs font-bold text-[#657584]">Aluno relacionado (opcional)</span><select className={fieldClass} value={message.studentId} onChange={event => setMessage({ ...message, studentId: event.target.value })}><option value="">Todos os alunos vinculados</option>{(accountOptions.find(account => account.id === Number(message.guardianId))?.students ?? []).map(student => <option key={student.id} value={student.id}>{student.name}</option>)}</select></label><label className="md:col-span-2 space-y-1.5"><span className="text-xs font-bold text-[#657584]">Assunto</span><Input required maxLength={160} placeholder="Ex.: Reunião de responsáveis" value={message.subject} onChange={event => setMessage({ ...message, subject: event.target.value })} /></label><label className="md:col-span-2 space-y-1.5"><span className="text-xs font-bold text-[#657584]">Mensagem</span><textarea required maxLength={5000} rows={5} className={`${fieldClass} h-auto py-3`} placeholder="Escreva o comunicado..." value={message.body} onChange={event => setMessage({ ...message, body: event.target.value })} /></label><div className="md:col-span-2 flex justify-end"><Button disabled={send.isPending} className="bg-[#14877e] text-white hover:bg-[#0f6e65]"><Send className="mr-2 h-4 w-4" />{send.isPending ? "Enviando..." : "Enviar comunicado"}</Button></div></form></CardContent></Card>
    <Card className="border-[#e6eae9] bg-white shadow-[0_12px_32px_rgba(26,54,73,.055)]"><CardContent className="p-5 sm:p-7"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#edf1f9] text-[#5470aa]"><MessageCircle className="h-5 w-5" /></div><div><h3 className="font-bold text-[#12233f]">Mensagens recebidas</h3><p className="text-xs text-[#647b79]">Acompanhe as solicitações enviadas pelos responsáveis.</p></div></div><div className="mt-5 space-y-3">{messages.data?.filter(item => item.direction === "fromGuardian").map(item => <div key={item.id} className="rounded-2xl border border-[#e8edeb] p-4"><div className="flex flex-wrap justify-between gap-2"><div><p className="font-semibold text-[#12233f]">{item.subject}</p><p className="mt-1 text-xs text-[#647b79]">{item.guardianName} · {item.email}{item.studentName ? ` · ${item.studentName}` : ""}</p></div><span className="text-xs text-[#789089]">{new Date(item.createdAt).toLocaleString("pt-BR")}</span></div><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-[#526374]">{item.body}</p></div>)}{!messages.isLoading && !(messages.data?.some(item => item.direction === "fromGuardian")) && <p className="rounded-xl bg-[#fbfdfb] p-5 text-center text-sm text-[#647b79]">Nenhuma mensagem recebida.</p>}</div></CardContent></Card>
  </div>;
}
