import { trpc } from "@/lib/trpc";
import { ArrowUpRight, BellRing, BookOpen, ClipboardList, Clock3, PackageOpen, Plus, TrendingDown, UserRound, UsersRound } from "lucide-react";
import { Link } from "wouter";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";

const formatDate = (value: Date | string | null | undefined) => value ? new Date(value).toLocaleDateString("pt-BR", { day: "2-digit", month: "short" }).replace(" de ", " ") : "—";
const typeLabels: Record<string, string> = { absence: "Falta", late: "Atraso", homework: "Tarefa não feita", book: "Livro esquecido", uniform: "Falta de uniforme", behavior: "Comportamento", other: "Outro" };

export default function Home() {
  const stats = trpc.school.dashboard.useQuery();
  const incidents = trpc.school.incidents.useQuery();
  const enrollments = trpc.school.enrollments.useQuery();
  const inventory = trpc.school.inventory.useQuery();
  const statCards = [
    { label: "Alunos ativos", value: stats.data?.students, hint: "cadastros ativos", icon: UsersRound, tone: "bg-[#e4f3ec] text-[#137669]" },
    { label: "Matrículas", value: stats.data?.enrollments, hint: `ano letivo ${new Date().getFullYear()}`, icon: BookOpen, tone: "bg-[#e9eff8] text-[#4f6eaa]" },
    { label: "Estoque baixo", value: stats.data?.lowStock, hint: "itens que precisam de atenção", icon: TrendingDown, tone: "bg-[#fff0df] text-[#ad6e2f]" },
    { label: "Anotações abertas", value: stats.data?.openIncidents, hint: "pendências para acompanhar", icon: ClipboardList, tone: "bg-[#faeae8] text-[#b76761]" },
  ];
  const lowStock = inventory.data?.filter(item => item.quantity <= item.minQuantity).slice(0, 4) ?? [];

  return <div className="mx-auto max-w-[1440px] space-y-6 sm:space-y-7">
    <section className="relative overflow-hidden rounded-[28px] bg-[#133b40] px-6 py-7 text-white shadow-[0_18px_48px_rgba(15,57,58,.12)] sm:px-9 sm:py-9 lg:px-11">
      <div aria-hidden="true" className="pointer-events-none absolute -right-24 -top-32 h-80 w-80 rounded-full border border-white/10 sm:h-[410px] sm:w-[410px]" />
      <div aria-hidden="true" className="pointer-events-none absolute -right-12 top-5 h-56 w-56 rounded-full bg-[#68b995]/15 blur-2xl sm:h-80 sm:w-80" />
      <div className="relative flex flex-col gap-6 md:flex-row md:items-end md:justify-between"><div className="max-w-xl"><span className="inline-flex rounded-full border border-[#bde8d1]/30 bg-[#bde8d1]/10 px-3 py-1.5 text-[11px] font-bold uppercase tracking-[.16em] text-[#bde8d1]">Visão geral do colégio</span><h2 className="mt-5 font-display text-3xl font-semibold leading-[1.1] tracking-tight sm:text-4xl lg:text-[42px]">A escola em movimento<span className="text-[#bde8d1]">.</span></h2><p className="mt-3 max-w-lg text-sm leading-6 text-[#d1e4db]">Alunos, matrículas e atividades do dia em uma visão mais clara para sua equipe.</p></div><div className="flex shrink-0 flex-col gap-2 2xl:flex-row"><Link href="/alunos" className="inline-flex min-h-11 items-center justify-center gap-2 whitespace-nowrap rounded-xl bg-[#bde8d1] px-5 py-3 text-sm font-bold text-[#143d37] transition hover:bg-white"><Plus className="h-4 w-4" /> Nova matrícula</Link><Link href="/anotacoes" className="inline-flex min-h-11 items-center justify-center gap-2 whitespace-nowrap rounded-xl border border-white/30 bg-white/5 px-5 py-3 text-sm font-bold text-white transition hover:bg-white/10"><ClipboardList className="h-4 w-4" /> Registrar anotação</Link></div></div>
    </section>

    <section aria-label="Indicadores do colégio" className="grid grid-cols-2 gap-3 sm:gap-4 xl:grid-cols-4">{statCards.map(item => <Card key={item.label} className="border border-[#e5ebe5] bg-white shadow-[0_7px_22px_rgba(25,58,51,.04)]"><CardContent className="p-4 sm:p-5"><div className="flex items-start justify-between"><div className={`grid h-10 w-10 place-items-center rounded-xl ${item.tone}`}><item.icon className="h-[19px] w-[19px]" /></div><ArrowUpRight className="h-4 w-4 text-[#8fa69a]" /></div><p className="mt-5 text-xs font-semibold text-[#516c6a]">{item.label}</p><p aria-busy={stats.isLoading} className="mt-1 font-display text-3xl font-semibold leading-none text-[#19383d] sm:text-[38px]">{stats.isLoading ? <span className="inline-block h-8 w-12 animate-pulse rounded-lg bg-[#e8efeb]" /> : stats.isError ? "—" : item.value ?? 0}</p><p className="mt-2 text-xs leading-4 text-[#657c79]">{stats.isError ? "Não foi possível carregar" : item.hint}</p></CardContent></Card>)}</section>

    <section className="grid gap-5 xl:grid-cols-[minmax(0,1.45fr)_minmax(300px,.85fr)]">
      <Card className="overflow-hidden border border-[#e5ebe5] bg-white shadow-[0_7px_22px_rgba(25,58,51,.04)]"><CardContent className="p-0"><div className="flex items-center justify-between gap-3 border-b border-[#edf1ed] px-5 py-5 sm:px-6"><div><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#fff1ea] text-[#b66d55]"><BellRing className="h-4 w-4" /></span><h3 className="font-display text-lg font-semibold text-[#203a40]">Anotações recentes</h3></div><p className="mt-1 text-xs leading-5 text-[#647b79]">Últimos registros da rotina escolar</p></div><Link href="/anotacoes" className="inline-flex shrink-0 items-center gap-1 rounded-lg px-2 py-2 text-xs font-bold text-[#0f796c] hover:bg-[#e8f5ee]">Ver todas <ArrowUpRight className="h-3.5 w-3.5" /></Link></div>
        <div className="min-h-64 divide-y divide-[#edf1ed]">{incidents.isLoading ? <div className="space-y-4 p-6" aria-label="Carregando anotações">{[1, 2, 3].map(n => <div key={n} className="h-12 animate-pulse rounded-xl bg-[#f1f5f1]" />)}</div> : incidents.isError ? <div role="alert" className="p-8 text-center text-sm text-[#ad5246]">Não foi possível carregar as anotações. Atualize a página para tentar novamente.</div> : incidents.data?.length ? incidents.data.slice(0, 5).map(incident => <div key={incident.id} className="flex items-start gap-3 px-5 py-4 sm:px-6"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-[#fff2e8] text-[#ae7153]"><ClipboardList className="h-4 w-4" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-bold text-[#29424a]">{incident.studentName ?? "Aluno"}</p><Badge variant="outline" className="border-[#efdacf] bg-[#fff9f4] px-2 py-0 text-[11px] font-semibold text-[#a4674d]">{typeLabels[incident.type]}</Badge></div><p className="mt-1 line-clamp-2 text-xs leading-5 text-[#617674]">{incident.note}</p></div><time className="shrink-0 pt-0.5 text-xs font-semibold text-[#68807c]">{formatDate(incident.occurredAt)}</time></div>) : <div className="grid min-h-64 place-content-center px-5 text-center"><span className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-[#eef6f0] text-[#2b8b72]"><ClipboardList className="h-5 w-5" /></span><p className="mt-3 text-sm font-bold text-[#36544e]">Tudo tranquilo por aqui</p><p className="mt-1 text-xs text-[#617674]">Quando houver anotações, elas aparecerão neste espaço.</p></div>}</div>
      </CardContent></Card>
      <div className="space-y-5">
        <Card className="border-0 bg-[#e6f2e9] shadow-[0_8px_24px_rgba(31,88,61,.06)]"><CardContent className="p-5 sm:p-6"><div className="flex items-start justify-between gap-3"><div><p className="text-[11px] font-bold uppercase tracking-[.16em] text-[#357a67]">Atenção ao estoque</p><h3 className="mt-2 font-display text-xl font-semibold text-[#173e37]">Itens para repor</h3></div><span className="grid h-9 w-9 place-items-center rounded-xl bg-white/80 text-[#2a7e68]"><PackageOpen className="h-5 w-5" /></span></div><div className="mt-5 space-y-3">{inventory.isLoading ? <div className="h-12 animate-pulse rounded-xl bg-white/70" /> : inventory.isError ? <p role="alert" className="text-sm text-[#a4473b]">Estoque temporariamente indisponível.</p> : lowStock.length ? lowStock.map(item => <div key={item.id} className="flex items-center justify-between gap-3 border-b border-[#b7d6c2] pb-3 last:border-0 last:pb-0"><div className="min-w-0"><p className="truncate text-sm font-semibold text-[#264940]">{item.name}</p><p className="mt-0.5 text-xs text-[#526e63]">{item.category === "uniform" ? "Uniforme" : item.category === "book" ? "Livro bimestral" : "Outro"}{item.size ? ` · ${item.size}` : ""}</p></div><span className="shrink-0 rounded-full bg-white px-2.5 py-1 text-xs font-bold text-[#ad6e2f]">{item.quantity} un.</span></div>) : <p className="text-sm text-[#456f60]">Tudo abastecido por aqui.</p>}</div><Link href="/estoque" className="mt-5 inline-flex min-h-10 items-center gap-1 text-xs font-bold text-[#0b6e5e] hover:underline">Abrir controle de estoque <ArrowUpRight className="h-4 w-4" /></Link></CardContent></Card>
        <Card className="border border-[#e5ebe5] bg-white shadow-[0_7px_22px_rgba(25,58,51,.04)]"><CardContent className="p-5 sm:p-6"><div className="flex items-center justify-between"><div><h3 className="font-display text-lg font-semibold text-[#203a40]">Últimas matrículas</h3><p className="mt-1 text-xs text-[#647b79]">Turmas do ano letivo</p></div><Clock3 className="h-5 w-5 text-[#73948a]" /></div><div className="mt-4 space-y-3">{enrollments.isLoading ? <div className="h-12 animate-pulse rounded-xl bg-[#f1f5f1]" /> : enrollments.isError ? <p role="alert" className="text-xs text-[#ad5246]">Não foi possível consultar as matrículas.</p> : enrollments.data?.length ? enrollments.data.slice(0, 3).map(enrollment => <div key={enrollment.id} className="flex items-center gap-3 border-b border-[#edf1ed] pb-3 last:border-0 last:pb-0"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-[#edf1f9] text-[#5470aa]"><UserRound className="h-4 w-4" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-[#365158]">{enrollment.studentName ?? "Aluno"}</p><p className="mt-0.5 text-xs text-[#657c79]">{enrollment.className} · {enrollment.schoolYear}</p></div><time className="text-xs font-medium text-[#728983]">{formatDate(enrollment.enrollmentDate)}</time></div>) : <div className="rounded-xl border border-dashed border-[#d8e6dc] bg-[#f8fbf8] p-4 text-center"><p className="text-sm font-semibold text-[#47675d]">Nenhuma matrícula ainda</p><Link href="/alunos" className="mt-2 inline-flex min-h-9 items-center text-xs font-bold text-[#0f796c] hover:underline">Cadastrar primeira matrícula <ArrowUpRight className="ml-1 h-3.5 w-3.5" /></Link></div>}</div></CardContent></Card>
      </div>
    </section>
  </div>;
}
