import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { toast } from "sonner";
import { ArrowDownLeft, ArrowUpRight, BookOpen, Package, Plus, Shirt, TriangleAlert } from "lucide-react";
import { useState } from "react";

const fieldClass = "h-10 w-full rounded-xl border border-[#dce5e3] bg-[#fbfcfb] px-3 text-xs text-[#3b4d60] outline-none transition placeholder:text-[#a9b3ba] focus:border-[#76c9bc] focus:ring-2 focus:ring-[#ccebe5]";
const categoryLabel: Record<string, string> = { uniform: "Uniforme", book: "Livro bimestral", other: "Outro" };

export default function Inventory() {
  const utils = trpc.useUtils();
  const inventory = trpc.school.inventory.useQuery();
  const [showForm, setShowForm] = useState(false);
  const [itemForm, setItemForm] = useState({ name: "", category: "uniform" as "uniform" | "book" | "other", size: "", quantity: "", minQuantity: "5", unitPrice: "" });
  const [movement, setMovement] = useState<{ itemId: string; type: "entry" | "exit"; quantity: string; reason: string } | null>(null);
  const addItem = trpc.school.addInventoryItem.useMutation({ onSuccess: () => { toast.success("Item adicionado ao estoque"); setItemForm({ name: "", category: "uniform", size: "", quantity: "", minQuantity: "5", unitPrice: "" }); setShowForm(false); utils.school.inventory.invalidate(); utils.school.dashboard.invalidate(); }, onError: error => toast.error(error.message) });
  const recordMovement = trpc.school.inventoryMovement.useMutation({ onSuccess: () => { toast.success("Movimentação registrada"); setMovement(null); utils.school.inventory.invalidate(); utils.school.dashboard.invalidate(); }, onError: error => toast.error(error.message) });
  const submitItem = (event: React.FormEvent) => { event.preventDefault(); if (!itemForm.name || !itemForm.quantity) return toast.error("Informe o nome e a quantidade inicial"); addItem.mutate({ name: itemForm.name, category: itemForm.category, size: itemForm.size || undefined, quantity: Number(itemForm.quantity), minQuantity: Number(itemForm.minQuantity || 0), unitPriceCents: Math.round(Number(itemForm.unitPrice || 0) * 100) }); };
  const submitMovement = (event: React.FormEvent) => { event.preventDefault(); if (!movement || !movement.quantity) return; recordMovement.mutate({ itemId: Number(movement.itemId), type: movement.type, quantity: Number(movement.quantity), reason: movement.reason || undefined }); };
  const totalUnits = inventory.data?.reduce((total, item) => total + item.quantity, 0) ?? 0;
  const lowCount = inventory.data?.filter(item => item.quantity <= item.minQuantity).length ?? 0;
  return <div className="mx-auto max-w-[1400px] space-y-6">
    <section className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="mb-2 text-xs font-bold uppercase tracking-[.2em] text-[#14877e]">Almoxarifado</p><h2 className="font-display text-3xl font-bold tracking-tight text-[#12233f]">Controle de estoque</h2><p className="mt-2 text-sm text-[#778592]">Uniformes, livros bimestrais e materiais da escola em um só lugar.</p></div><button onClick={() => setShowForm(!showForm)} className="inline-flex items-center gap-2 self-start rounded-xl bg-[#12233f] px-4 py-3 text-xs font-bold text-white shadow-[0_8px_18px_rgba(18,35,63,.15)] transition hover:-translate-y-0.5 md:self-auto"><Plus className="h-4 w-4" /> Novo item</button></section>
    <section className="grid gap-4 sm:grid-cols-3"><Card className="border-0 bg-white shadow-[0_7px_25px_rgba(26,54,73,.05)]"><CardContent className="flex items-center gap-4 p-5"><div className="grid h-11 w-11 place-items-center rounded-xl bg-[#e7f4f1] text-[#14877e]"><Package className="h-5 w-5" /></div><div><p className="text-[11px] font-semibold text-[#87949e]">Itens cadastrados</p><p className="mt-1 text-2xl font-bold text-[#12233f]">{inventory.data?.length ?? 0}</p></div></CardContent></Card><Card className="border-0 bg-white shadow-[0_7px_25px_rgba(26,54,73,.05)]"><CardContent className="flex items-center gap-4 p-5"><div className="grid h-11 w-11 place-items-center rounded-xl bg-[#edf1f9] text-[#5470aa]"><BoxIcon /></div><div><p className="text-[11px] font-semibold text-[#87949e]">Unidades em estoque</p><p className="mt-1 text-2xl font-bold text-[#12233f]">{totalUnits}</p></div></CardContent></Card><Card className="border-0 bg-white shadow-[0_7px_25px_rgba(26,54,73,.05)]"><CardContent className="flex items-center gap-4 p-5"><div className="grid h-11 w-11 place-items-center rounded-xl bg-[#fff0df] text-[#c2772d]"><TriangleAlert className="h-5 w-5" /></div><div><p className="text-[11px] font-semibold text-[#87949e]">Abaixo do mínimo</p><p className="mt-1 text-2xl font-bold text-[#12233f]">{lowCount}</p></div></CardContent></Card></section>
    {showForm && <Card className="border-0 bg-white shadow-[0_7px_25px_rgba(26,54,73,.05)]"><CardContent className="p-5"><div className="mb-5 flex items-center justify-between"><div><h3 className="text-sm font-bold text-[#253b55]">Adicionar item ao estoque</h3><p className="mt-1 text-[11px] text-[#9aa5ae]">Cadastre o item e defina o estoque mínimo.</p></div><Package className="h-5 w-5 text-[#14877e]" /></div><form onSubmit={submitItem} className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><label className="lg:col-span-2"><span className="mb-1.5 block text-[11px] font-bold text-[#657584]">Nome do item *</span><input className={fieldClass} placeholder="Ex.: Camiseta branca" value={itemForm.name} onChange={e => setItemForm({ ...itemForm, name: e.target.value })} /></label><label><span className="mb-1.5 block text-[11px] font-bold text-[#657584]">Categoria</span><select className={fieldClass} value={itemForm.category} onChange={e => setItemForm({ ...itemForm, category: e.target.value as typeof itemForm.category })}><option value="uniform">Uniforme</option><option value="book">Livro bimestral</option><option value="other">Outro</option></select></label><label><span className="mb-1.5 block text-[11px] font-bold text-[#657584]">Tamanho</span><input className={fieldClass} placeholder="M, 10, único..." value={itemForm.size} onChange={e => setItemForm({ ...itemForm, size: e.target.value })} /></label><label><span className="mb-1.5 block text-[11px] font-bold text-[#657584]">Qtd. inicial *</span><input type="number" min="0" className={fieldClass} placeholder="0" value={itemForm.quantity} onChange={e => setItemForm({ ...itemForm, quantity: e.target.value })} /></label><label><span className="mb-1.5 block text-[11px] font-bold text-[#657584]">Estoque mínimo</span><input type="number" min="0" className={fieldClass} value={itemForm.minQuantity} onChange={e => setItemForm({ ...itemForm, minQuantity: e.target.value })} /></label><label><span className="mb-1.5 block text-[11px] font-bold text-[#657584]">Preço unitário</span><input type="number" min="0" step="0.01" className={fieldClass} placeholder="R$ 0,00" value={itemForm.unitPrice} onChange={e => setItemForm({ ...itemForm, unitPrice: e.target.value })} /></label><div className="flex items-end justify-end gap-2 lg:col-span-2"><button type="button" onClick={() => setShowForm(false)} className="rounded-xl px-4 py-2.5 text-xs font-bold text-[#7d8b96] hover:bg-[#f5f7f6]">Cancelar</button><button disabled={addItem.isPending} className="rounded-xl bg-[#14877e] px-4 py-2.5 text-xs font-bold text-white disabled:opacity-50">{addItem.isPending ? "Salvando..." : "Salvar item"}</button></div></form></CardContent></Card>}
    <Card className="border-0 bg-white shadow-[0_7px_25px_rgba(26,54,73,.05)]"><CardContent className="p-0"><div className="hidden grid-cols-[1.5fr_.8fr_.6fr_.7fr_1fr] gap-4 border-b border-[#edf0ef] px-5 py-4 text-[10px] font-bold uppercase tracking-[.12em] text-[#9aa5ae] md:grid"><span>Item</span><span>Categoria</span><span>Qtd.</span><span>Status</span><span className="text-right">Ação</span></div><div className="divide-y divide-[#f0f2f1]">{inventory.isLoading ? <div className="p-8 text-center text-sm text-[#9aa5ae]">Carregando estoque...</div> : inventory.data?.length ? inventory.data.map(item => { const low = item.quantity <= item.minQuantity; return <div key={item.id} className="grid gap-3 px-5 py-4 md:grid-cols-[1.5fr_.8fr_.6fr_.7fr_1fr] md:items-center md:gap-4"><div className="flex items-center gap-3"><div className={`grid h-9 w-9 place-items-center rounded-lg ${item.category === "uniform" ? "bg-[#f9e7e7] text-[#b75b5b]" : item.category === "book" ? "bg-[#edf1f9] text-[#5470aa]" : "bg-[#f1f1ee] text-[#7b857b]"}`}>{item.category === "uniform" ? <Shirt className="h-4 w-4" /> : item.category === "book" ? <BookOpen className="h-4 w-4" /> : <Package className="h-4 w-4" />}</div><div><p className="text-xs font-bold text-[#3b4d60]">{item.name}</p><p className="mt-1 text-[10px] text-[#9aa5ae]">{item.size ? `Tamanho ${item.size}` : "Sem tamanho específico"}</p></div></div><span className="text-[11px] font-semibold text-[#667685] md:block">{categoryLabel[item.category]}</span><span className="text-xs font-bold text-[#253b55]">{item.quantity} <span className="font-normal text-[#a2adb4]">un.</span></span><span><Badge className={`border-0 text-[9px] font-bold ${low ? "bg-[#fff0df] text-[#c2772d]" : "bg-[#e7f4f1] text-[#14877e]"}`}>{low ? "Repor" : "Disponível"}</Badge></span><button onClick={() => setMovement({ itemId: String(item.id), type: "entry", quantity: "", reason: "" })} className="inline-flex items-center justify-center gap-1.5 justify-self-start rounded-lg border border-[#d9e2e1] px-3 py-2 text-[10px] font-bold text-[#526374] transition hover:border-[#8ccfc2] md:justify-self-end"><ArrowUpRight className="h-3.5 w-3.5 text-[#14877e]" /> Movimentar</button></div> }) : <div className="p-8 text-center text-sm text-[#9aa5ae]">Nenhum item cadastrado.</div>}</div></CardContent></Card>
    {movement && <div className="fixed inset-0 z-50 grid place-items-center bg-[#12233f]/25 p-4 backdrop-blur-sm"><Card className="w-full max-w-md border-0 bg-white shadow-2xl"><CardContent className="p-6"><div className="mb-5 flex items-center justify-between"><div><h3 className="text-base font-bold text-[#253b55]">Registrar movimentação</h3><p className="mt-1 text-[11px] text-[#9aa5ae]">Atualize a quantidade disponível.</p></div><Package className="h-5 w-5 text-[#14877e]" /></div><form onSubmit={submitMovement} className="space-y-4"><label className="block"><span className="mb-1.5 block text-[11px] font-bold text-[#657584]">Tipo</span><div className="grid grid-cols-2 gap-2"><button type="button" onClick={() => setMovement({ ...movement, type: "entry" })} className={`flex items-center justify-center gap-2 rounded-xl border p-3 text-xs font-bold ${movement.type === "entry" ? "border-[#8ccfc2] bg-[#e7f4f1] text-[#14877e]" : "border-[#dce5e3] text-[#8996a0]"}`}><ArrowDownLeft className="h-4 w-4" /> Entrada</button><button type="button" onClick={() => setMovement({ ...movement, type: "exit" })} className={`flex items-center justify-center gap-2 rounded-xl border p-3 text-xs font-bold ${movement.type === "exit" ? "border-[#edb9a8] bg-[#fff3ee] text-[#b96046]" : "border-[#dce5e3] text-[#8996a0]"}`}><ArrowUpRight className="h-4 w-4" /> Saída</button></div></label><label className="block"><span className="mb-1.5 block text-[11px] font-bold text-[#657584]">Quantidade *</span><input type="number" min="1" className={fieldClass} value={movement.quantity} onChange={e => setMovement({ ...movement, quantity: e.target.value })} /></label><label className="block"><span className="mb-1.5 block text-[11px] font-bold text-[#657584]">Motivo</span><input className={fieldClass} placeholder="Ex.: entrega para turma 5º A" value={movement.reason} onChange={e => setMovement({ ...movement, reason: e.target.value })} /></label><div className="flex justify-end gap-2"><button type="button" onClick={() => setMovement(null)} className="rounded-xl px-4 py-2.5 text-xs font-bold text-[#7d8b96] hover:bg-[#f5f7f6]">Cancelar</button><button disabled={recordMovement.isPending} className="rounded-xl bg-[#14877e] px-4 py-2.5 text-xs font-bold text-white disabled:opacity-50">{recordMovement.isPending ? "Salvando..." : "Confirmar"}</button></div></form></CardContent></Card></div>}
  </div>;
}

function BoxIcon() { return <Package className="h-5 w-5" />; }
