import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { toast } from "sonner";
import { GraduationCap, IdCard, Mail, MapPin, Phone, Plus, Search, Trash2, UserPlus, X } from "lucide-react";
import { useState } from "react";

const fieldClass = "h-10 w-full rounded-xl border border-[#dce5e3] bg-[#fbfcfb] px-3 text-xs text-[#3b4d60] outline-none transition placeholder:text-[#a9b3ba] focus:border-[#76c9bc] focus:ring-2 focus:ring-[#ccebe5]";
const onlyDigits = (value: string) => value.replace(/\D/g, "");
const formatCpf = (value: string) => onlyDigits(value).slice(0, 11).replace(/^(\d{3})(\d)/, "$1.$2").replace(/^(\d{3})\.(\d{3})(\d)/, "$1.$2.$3").replace(/(\d{3}\.\d{3}\.\d{3})(\d{1,2})$/, "$1-$2");
const formatPhone = (value: string) => { const digits = onlyDigits(value).slice(0, 11); if (digits.length <= 2) return digits; if (digits.length <= 6) return `(${digits.slice(0, 2)}) ${digits.slice(2)}`; return `(${digits.slice(0, 2)}) ${digits.slice(2, -4)}-${digits.slice(-4)}`; };
const newStudent = () => ({ name: "", grade: "", birthDate: "", cpf: "", guardianName: "", guardianCpf: "", guardianEmail: "", address: "", phones: [""] });

export default function Students() {
  const utils = trpc.useUtils();
  const students = trpc.school.students.useQuery();
  const enrollments = trpc.school.enrollments.useQuery();
  const [search, setSearch] = useState("");
  const [showStudentForm, setShowStudentForm] = useState(false);
  const [showEnrollmentForm, setShowEnrollmentForm] = useState(false);
  const [studentForm, setStudentForm] = useState(newStudent);
  const [viewStudentId, setViewStudentId] = useState<number | null>(null);
  const [enrollmentForm, setEnrollmentForm] = useState({ studentId: "", schoolYear: String(new Date().getFullYear()), className: "", shift: "morning" as "morning" | "afternoon" | "fulltime" });
  const addStudent = trpc.school.addStudent.useMutation({ onSuccess: student => { toast.success("Aluno cadastrado. Agora conclua a matrícula."); setStudentForm(newStudent()); setShowStudentForm(false); setEnrollmentForm(current => ({ ...current, studentId: String(student.id) })); setShowEnrollmentForm(true); utils.school.students.invalidate(); utils.school.dashboard.invalidate(); }, onError: error => toast.error(error.message) });
  const addEnrollment = trpc.school.addEnrollment.useMutation({ onSuccess: () => { toast.success("Matrícula registrada"); setEnrollmentForm({ studentId: "", schoolYear: String(new Date().getFullYear()), className: "", shift: "morning" }); setShowEnrollmentForm(false); utils.school.enrollments.invalidate(); utils.school.dashboard.invalidate(); }, onError: error => toast.error(error.message) });
  const filtered = students.data?.filter(student => `${student.name} ${student.grade} ${student.guardianName}`.toLowerCase().includes(search.toLowerCase())) ?? [];
  const selectedStudent = students.data?.find(student => student.id === viewStudentId);
  const changePhone = (index: number, value: string) => setStudentForm(current => ({ ...current, phones: current.phones.map((phone, position) => position === index ? formatPhone(value) : phone) }));
  const submitStudent = (event: React.FormEvent) => {
    event.preventDefault();
    if (studentForm.phones.some(phone => ![10, 11].includes(onlyDigits(phone).length))) return toast.error("Informe telefone(s) com DDD, sem campos vazios.");
    if (onlyDigits(studentForm.cpf).length !== 11 || onlyDigits(studentForm.guardianCpf).length !== 11) return toast.error("Informe os dois CPFs com 11 dígitos.");
    addStudent.mutate({ ...studentForm, name: studentForm.name.trim(), grade: studentForm.grade.trim(), guardianName: studentForm.guardianName.trim(), guardianEmail: studentForm.guardianEmail.trim(), address: studentForm.address.trim(), cpf: onlyDigits(studentForm.cpf), guardianCpf: onlyDigits(studentForm.guardianCpf), phones: studentForm.phones.map(onlyDigits) });
  };
  const submitEnrollment = (event: React.FormEvent) => { event.preventDefault(); if (!enrollmentForm.studentId || !enrollmentForm.className) return toast.error("Selecione um aluno e informe a turma"); addEnrollment.mutate({ ...enrollmentForm, studentId: Number(enrollmentForm.studentId) }); };
  return <div className="mx-auto max-w-[1400px] space-y-6">
    <section className="flex flex-col justify-between gap-4 md:flex-row md:items-end">
      <div><p className="mb-2 text-xs font-bold uppercase tracking-[.2em] text-[#14877e]">Cadastros</p><h2 className="font-display text-3xl font-bold tracking-tight text-[#12233f]">Alunos e matrículas</h2><p className="mt-2 text-sm text-[#778592]">Mantenha os dados dos estudantes, responsáveis e o ano letivo organizados.</p></div>
      <div className="flex flex-wrap gap-2"><button onClick={() => setShowEnrollmentForm(!showEnrollmentForm)} className="inline-flex items-center gap-2 rounded-xl border border-[#d9e2e1] bg-white px-4 py-3 text-xs font-bold text-[#526374] transition hover:border-[#8ccfc2]"><GraduationCap className="h-4 w-4 text-[#14877e]" /> Nova matrícula</button><button onClick={() => setShowStudentForm(!showStudentForm)} className="inline-flex items-center gap-2 rounded-xl bg-[#12233f] px-4 py-3 text-xs font-bold text-white shadow-[0_8px_18px_rgba(18,35,63,.15)] transition hover:-translate-y-0.5"><Plus className="h-4 w-4" /> Novo aluno</button></div>
    </section>
    {(showStudentForm || showEnrollmentForm) && <section className={`grid items-start gap-5 ${showStudentForm && showEnrollmentForm ? "xl:grid-cols-2" : showStudentForm ? "max-w-3xl" : "max-w-xl"}`}>
      {showStudentForm && <Card className="border-0 bg-white shadow-[0_7px_25px_rgba(26,54,73,.05)]"><CardContent className="p-5"><div className="mb-5 flex items-center justify-between"><div><h3 className="text-sm font-bold text-[#253b55]">Cadastrar aluno e responsável</h3><p className="mt-1 text-[11px] text-[#9aa5ae]">Preencha os contatos antes de registrar a matrícula.</p></div><UserPlus className="h-5 w-5 text-[#14877e]" /></div>
        <form onSubmit={submitStudent} className="grid gap-3 sm:grid-cols-2">
          <p className="sm:col-span-2 text-[10px] font-bold uppercase tracking-[.15em] text-[#14877e]">Dados do aluno</p>
          <label className="sm:col-span-2"><span className="mb-1.5 block text-[11px] font-bold text-[#657584]">Nome completo *</span><input required maxLength={160} className={fieldClass} placeholder="Ex.: Helena Martins" value={studentForm.name} onChange={e => setStudentForm({ ...studentForm, name: e.target.value })} /></label>
          <label><span className="mb-1.5 block text-[11px] font-bold text-[#657584]">Turma / série *</span><input required maxLength={80} className={fieldClass} placeholder="Ex.: 5º ano A" value={studentForm.grade} onChange={e => setStudentForm({ ...studentForm, grade: e.target.value })} /></label>
          <label><span className="mb-1.5 block text-[11px] font-bold text-[#657584]">Data de nascimento</span><input type="date" className={fieldClass} value={studentForm.birthDate} onChange={e => setStudentForm({ ...studentForm, birthDate: e.target.value })} /></label>
          <label className="sm:col-span-2"><span className="mb-1.5 block text-[11px] font-bold text-[#657584]">CPF do aluno *</span><input required inputMode="numeric" autoComplete="off" maxLength={14} className={fieldClass} placeholder="000.000.000-00" value={studentForm.cpf} onChange={e => setStudentForm({ ...studentForm, cpf: formatCpf(e.target.value) })} /></label>
          <div className="sm:col-span-2 mt-1 border-t border-[#edf0ef] pt-4"><p className="text-[10px] font-bold uppercase tracking-[.15em] text-[#14877e]">Dados do responsável</p></div>
          <label className="sm:col-span-2"><span className="mb-1.5 block text-[11px] font-bold text-[#657584]">Nome completo *</span><input required maxLength={160} className={fieldClass} placeholder="Nome do responsável" value={studentForm.guardianName} onChange={e => setStudentForm({ ...studentForm, guardianName: e.target.value })} /></label>
          <label><span className="mb-1.5 block text-[11px] font-bold text-[#657584]">CPF do responsável *</span><input required inputMode="numeric" autoComplete="off" maxLength={14} className={fieldClass} placeholder="000.000.000-00" value={studentForm.guardianCpf} onChange={e => setStudentForm({ ...studentForm, guardianCpf: formatCpf(e.target.value) })} /></label>
          <label><span className="mb-1.5 block text-[11px] font-bold text-[#657584]">E-mail do responsável *</span><input type="email" required maxLength={320} className={fieldClass} placeholder="responsavel@exemplo.com" value={studentForm.guardianEmail} onChange={e => setStudentForm({ ...studentForm, guardianEmail: e.target.value })} /></label>
          <label className="sm:col-span-2"><span className="mb-1.5 block text-[11px] font-bold text-[#657584]">Endereço completo *</span><input required minLength={8} maxLength={500} className={fieldClass} placeholder="Rua, número, complemento, bairro, cidade e CEP" value={studentForm.address} onChange={e => setStudentForm({ ...studentForm, address: e.target.value })} /></label>
          <div className="sm:col-span-2"><div className="mb-1.5 flex items-center justify-between gap-2"><span className="text-[11px] font-bold text-[#657584]">Telefones do responsável *</span><button type="button" disabled={studentForm.phones.length >= 20} onClick={() => setStudentForm(current => ({ ...current, phones: [...current.phones, ""] }))} className="inline-flex items-center gap-1 text-[11px] font-bold text-[#14877e] disabled:opacity-40"><Plus className="h-3.5 w-3.5" /> Adicionar número</button></div><div className="space-y-2">{studentForm.phones.map((phone, index) => <div className="flex gap-2" key={index}><input type="tel" required inputMode="tel" maxLength={15} aria-label={`Telefone ${index + 1} do responsável`} className={fieldClass} placeholder="(00) 00000-0000" value={phone} onChange={e => changePhone(index, e.target.value)} /><button type="button" disabled={studentForm.phones.length === 1} onClick={() => setStudentForm(current => ({ ...current, phones: current.phones.filter((_, position) => position !== index) }))} className="grid h-10 w-10 shrink-0 place-items-center rounded-xl text-[#b96046] hover:bg-[#fff3ee] disabled:opacity-30" aria-label={`Remover telefone ${index + 1}`}><Trash2 className="h-4 w-4" /></button></div>)}</div></div>
          <div className="flex justify-end gap-2 pt-2 sm:col-span-2"><button type="button" onClick={() => setShowStudentForm(false)} className="rounded-xl px-4 py-2.5 text-xs font-bold text-[#7d8b96] hover:bg-[#f5f7f6]">Cancelar</button><button disabled={addStudent.isPending} className="rounded-xl bg-[#14877e] px-4 py-2.5 text-xs font-bold text-white disabled:opacity-50">{addStudent.isPending ? "Salvando..." : "Salvar aluno"}</button></div>
        </form></CardContent></Card>}
      {showEnrollmentForm && <Card className="border-0 bg-white shadow-[0_7px_25px_rgba(26,54,73,.05)]"><CardContent className="p-5"><div className="mb-5 flex items-center justify-between"><div><h3 className="text-sm font-bold text-[#253b55]">Registrar matrícula</h3><p className="mt-1 text-[11px] text-[#9aa5ae]">Selecione um aluno já cadastrado e vincule-o à turma.</p></div><GraduationCap className="h-5 w-5 text-[#4268aa]" /></div><form onSubmit={submitEnrollment} className="grid gap-3 sm:grid-cols-2"><label className="sm:col-span-2"><span className="mb-1.5 block text-[11px] font-bold text-[#657584]">Aluno *</span><select required className={fieldClass} value={enrollmentForm.studentId} onChange={e => setEnrollmentForm({ ...enrollmentForm, studentId: e.target.value })}><option value="">Selecione um aluno</option>{students.data?.map(student => <option key={student.id} value={student.id}>{student.name} · {student.grade}</option>)}</select></label><label><span className="mb-1.5 block text-[11px] font-bold text-[#657584]">Ano letivo *</span><input required className={fieldClass} value={enrollmentForm.schoolYear} onChange={e => setEnrollmentForm({ ...enrollmentForm, schoolYear: e.target.value })} /></label><label><span className="mb-1.5 block text-[11px] font-bold text-[#657584]">Turma *</span><input required className={fieldClass} placeholder="Ex.: 5º ano A" value={enrollmentForm.className} onChange={e => setEnrollmentForm({ ...enrollmentForm, className: e.target.value })} /></label><label><span className="mb-1.5 block text-[11px] font-bold text-[#657584]">Turno</span><select className={fieldClass} value={enrollmentForm.shift} onChange={e => setEnrollmentForm({ ...enrollmentForm, shift: e.target.value as typeof enrollmentForm.shift })}><option value="morning">Manhã</option><option value="afternoon">Tarde</option><option value="fulltime">Integral</option></select></label><div className="flex justify-end gap-2 sm:col-span-2"><button type="button" onClick={() => setShowEnrollmentForm(false)} className="rounded-xl px-4 py-2.5 text-xs font-bold text-[#7d8b96] hover:bg-[#f5f7f6]">Cancelar</button><button disabled={addEnrollment.isPending} className="rounded-xl bg-[#4268aa] px-4 py-2.5 text-xs font-bold text-white disabled:opacity-50">{addEnrollment.isPending ? "Salvando..." : "Salvar matrícula"}</button></div></form></CardContent></Card>}
    </section>}
    <section className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]">
      <Card className="border-0 bg-white shadow-[0_7px_25px_rgba(26,54,73,.05)]"><CardContent className="p-0"><div className="flex flex-col justify-between gap-3 border-b border-[#edf0ef] px-5 py-5 sm:flex-row sm:items-center"><div><h3 className="text-sm font-bold text-[#253b55]">Estudantes cadastrados</h3><p className="mt-1 text-[11px] text-[#9aa5ae]">{filtered.length} aluno(s) encontrado(s)</p></div><div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-[#a7b2b9]" /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Buscar aluno..." className="h-9 w-full rounded-lg border border-[#e4eae8] bg-[#fbfcfb] pl-9 pr-3 text-xs outline-none focus:border-[#76c9bc] sm:w-52" /></div></div><div className="divide-y divide-[#f0f2f1]">{students.isLoading ? <div className="p-8 text-center text-sm text-[#9aa5ae]">Carregando alunos...</div> : students.isError ? <div className="p-8 text-center text-sm text-[#b96046]">Não foi possível carregar os alunos. Tente atualizar a página.</div> : filtered.length ? filtered.map(student => <div key={student.id} className="flex flex-wrap items-center gap-3 px-5 py-4"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-[#e8f3f1] text-xs font-bold text-[#14877e]">{student.name.split(" ").map(part => part[0]).slice(0, 2).join("")}</div><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold text-[#3b4d60]">{student.name}</p><p className="mt-1 truncate text-[11px] text-[#8d99a3]">{student.grade} · responsável: {student.guardianName}</p></div><div className="hidden items-center gap-1 text-[10px] text-[#8d99a3] sm:flex"><Phone className="h-3 w-3" />{student.phones[0] ? formatPhone(student.phones[0]) : "Sem telefone"}</div><button type="button" onClick={() => setViewStudentId(student.id)} className="rounded-lg border border-[#dce8e5] px-2.5 py-1.5 text-[10px] font-bold text-[#14877e] hover:bg-[#e7f4f1]">Ver cadastro</button><Badge className="border-0 bg-[#e7f4f1] text-[9px] font-bold text-[#14877e]">Ativo</Badge></div>) : <div className="p-8 text-center text-sm text-[#9aa5ae]">Nenhum aluno encontrado.</div>}</div></CardContent></Card>
      <Card className="border-0 bg-white shadow-[0_7px_25px_rgba(26,54,73,.05)]"><CardContent className="p-0"><div className="border-b border-[#edf0ef] px-5 py-5"><h3 className="text-sm font-bold text-[#253b55]">Matrículas recentes</h3><p className="mt-1 text-[11px] text-[#9aa5ae]">Vínculos ativos com o ano letivo</p></div><div className="divide-y divide-[#f0f2f1]">{enrollments.data?.length ? enrollments.data.slice(0, 8).map(enrollment => <div key={enrollment.id} className="flex items-center gap-3 px-5 py-4"><div className="grid h-8 w-8 place-items-center rounded-lg bg-[#edf1f9] text-[#5470aa]"><GraduationCap className="h-4 w-4" /></div><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold text-[#3b4d60]">{enrollment.studentName ?? "Aluno"}</p><p className="mt-1 text-[10px] text-[#8d99a3]">{enrollment.className} · {enrollment.shift === "morning" ? "Manhã" : enrollment.shift === "afternoon" ? "Tarde" : "Integral"}</p></div><Badge variant="outline" className="border-[#d9e6f6] bg-[#f6f8fd] text-[9px] font-bold text-[#5470aa]">{enrollment.schoolYear}</Badge></div>) : <div className="p-8 text-center text-sm text-[#9aa5ae]">Ainda não há matrículas.</div>}</div></CardContent></Card>
    </section>
    {selectedStudent && <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-[#12233f]/35 p-4 backdrop-blur-sm" role="presentation" onMouseDown={e => { if (e.target === e.currentTarget) setViewStudentId(null); }}><Card role="dialog" aria-modal="true" aria-label={`Cadastro de ${selectedStudent.name}`} className="w-full max-w-lg border-0 bg-white shadow-2xl"><CardContent className="p-6"><div className="mb-5 flex items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.15em] text-[#14877e]">Cadastro do aluno</p><h3 className="mt-2 text-xl font-bold text-[#12233f]">{selectedStudent.name}</h3><p className="mt-1 text-xs text-[#778592]">{selectedStudent.grade}</p></div><button type="button" onClick={() => setViewStudentId(null)} aria-label="Fechar cadastro" className="grid h-8 w-8 place-items-center rounded-lg text-[#64748b] hover:bg-[#f1f5f4]"><X className="h-4 w-4" /></button></div><div className="space-y-4 text-xs text-[#526374]"><div className="rounded-xl bg-[#f6faf9] p-4"><p className="mb-3 text-[10px] font-bold uppercase tracking-wide text-[#14877e]">Aluno</p><p className="flex items-center gap-2"><IdCard className="h-4 w-4" /> CPF: {selectedStudent.cpf ? formatCpf(selectedStudent.cpf) : "Não informado (cadastro antigo)"}</p>{selectedStudent.birthDate && <p className="mt-2">Nascimento: {selectedStudent.birthDate.split("-").reverse().join("/")}</p>}</div><div className="rounded-xl bg-[#f8f9fc] p-4"><p className="mb-3 text-[10px] font-bold uppercase tracking-wide text-[#5470aa]">Responsável: {selectedStudent.guardianName}</p><p className="flex items-center gap-2"><IdCard className="h-4 w-4" /> CPF: {selectedStudent.guardianCpf ? formatCpf(selectedStudent.guardianCpf) : "Não informado"}</p><p className="mt-2 flex items-start gap-2 break-words"><Mail className="h-4 w-4 shrink-0" />{selectedStudent.guardianEmail || "E-mail não informado"}</p><p className="mt-2 flex items-start gap-2 break-words"><MapPin className="h-4 w-4 shrink-0" />{selectedStudent.address || "Endereço não informado"}</p><div className="mt-3 flex items-start gap-2"><Phone className="h-4 w-4 shrink-0" /><div>{selectedStudent.phones.length ? selectedStudent.phones.map((phone, index) => <p key={`${phone}-${index}`} className={index ? "mt-1" : ""}>{formatPhone(phone)}</p>) : "Sem telefone"}</div></div></div></div></CardContent></Card></div>}
  </div>;
}
