import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { toast } from "sonner";
import { GraduationCap, Phone, Plus, Search, UserPlus, UsersRound } from "lucide-react";
import { useState } from "react";

const fieldClass = "h-10 w-full rounded-xl border border-[#dce5e3] bg-[#fbfcfb] px-3 text-xs text-[#3b4d60] outline-none transition placeholder:text-[#a9b3ba] focus:border-[#76c9bc] focus:ring-2 focus:ring-[#ccebe5]";

export default function Students() {
  const utils = trpc.useUtils();
  const students = trpc.school.students.useQuery();
  const enrollments = trpc.school.enrollments.useQuery();
  const [search, setSearch] = useState("");
  const [showStudentForm, setShowStudentForm] = useState(false);
  const [showEnrollmentForm, setShowEnrollmentForm] = useState(false);
  const [studentForm, setStudentForm] = useState({ name: "", grade: "", guardianName: "", guardianPhone: "", birthDate: "" });
  const [enrollmentForm, setEnrollmentForm] = useState({ studentId: "", schoolYear: "2026", className: "", shift: "morning" as "morning" | "afternoon" | "fulltime" });
  const addStudent = trpc.school.addStudent.useMutation({ onSuccess: () => { toast.success("Aluno cadastrado com sucesso"); setStudentForm({ name: "", grade: "", guardianName: "", guardianPhone: "", birthDate: "" }); setShowStudentForm(false); utils.school.students.invalidate(); utils.school.dashboard.invalidate(); }, onError: error => toast.error(error.message) });
  const addEnrollment = trpc.school.addEnrollment.useMutation({ onSuccess: () => { toast.success("Matrícula registrada"); setEnrollmentForm({ studentId: "", schoolYear: "2026", className: "", shift: "morning" }); setShowEnrollmentForm(false); utils.school.enrollments.invalidate(); utils.school.dashboard.invalidate(); }, onError: error => toast.error(error.message) });
  const filtered = students.data?.filter(student => `${student.name} ${student.grade} ${student.guardianName}`.toLowerCase().includes(search.toLowerCase())) ?? [];
  const submitStudent = (event: React.FormEvent) => { event.preventDefault(); if (!studentForm.name || !studentForm.grade || !studentForm.guardianName) return toast.error("Preencha nome, turma e responsável"); addStudent.mutate(studentForm); };
  const submitEnrollment = (event: React.FormEvent) => { event.preventDefault(); if (!enrollmentForm.studentId || !enrollmentForm.className) return toast.error("Selecione um aluno e informe a turma"); addEnrollment.mutate({ ...enrollmentForm, studentId: Number(enrollmentForm.studentId) }); };
  return <div className="mx-auto max-w-[1400px] space-y-6">
    <section className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="mb-2 text-xs font-bold uppercase tracking-[.2em] text-[#14877e]">Cadastros</p><h2 className="font-display text-3xl font-bold tracking-tight text-[#12233f]">Alunos e matrículas</h2><p className="mt-2 text-sm text-[#778592]">Mantenha os dados dos estudantes e o ano letivo organizados.</p></div><div className="flex gap-2"><button onClick={() => setShowEnrollmentForm(!showEnrollmentForm)} className="inline-flex items-center gap-2 rounded-xl border border-[#d9e2e1] bg-white px-4 py-3 text-xs font-bold text-[#526374] transition hover:border-[#8ccfc2]"><GraduationCap className="h-4 w-4 text-[#14877e]" /> Nova matrícula</button><button onClick={() => setShowStudentForm(!showStudentForm)} className="inline-flex items-center gap-2 rounded-xl bg-[#12233f] px-4 py-3 text-xs font-bold text-white shadow-[0_8px_18px_rgba(18,35,63,.15)] transition hover:-translate-y-0.5"><Plus className="h-4 w-4" /> Novo aluno</button></div></section>
    {(showStudentForm || showEnrollmentForm) && <section className="grid gap-5 xl:grid-cols-2">
      {showStudentForm && <Card className="border-0 bg-white shadow-[0_7px_25px_rgba(26,54,73,.05)]"><CardContent className="p-5"><div className="mb-5 flex items-center justify-between"><div><h3 className="text-sm font-bold text-[#253b55]">Cadastrar aluno</h3><p className="mt-1 text-[11px] text-[#9aa5ae]">Os campos com * são obrigatórios.</p></div><UserPlus className="h-5 w-5 text-[#14877e]" /></div><form onSubmit={submitStudent} className="grid gap-3 sm:grid-cols-2"><label className="sm:col-span-2"><span className="mb-1.5 block text-[11px] font-bold text-[#657584]">Nome completo *</span><input className={fieldClass} placeholder="Ex.: Helena Martins" value={studentForm.name} onChange={e => setStudentForm({ ...studentForm, name: e.target.value })} /></label><label><span className="mb-1.5 block text-[11px] font-bold text-[#657584]">Turma / série *</span><input className={fieldClass} placeholder="Ex.: 5º ano A" value={studentForm.grade} onChange={e => setStudentForm({ ...studentForm, grade: e.target.value })} /></label><label><span className="mb-1.5 block text-[11px] font-bold text-[#657584]">Data de nascimento</span><input type="date" className={fieldClass} value={studentForm.birthDate} onChange={e => setStudentForm({ ...studentForm, birthDate: e.target.value })} /></label><label><span className="mb-1.5 block text-[11px] font-bold text-[#657584]">Responsável *</span><input className={fieldClass} placeholder="Nome do responsável" value={studentForm.guardianName} onChange={e => setStudentForm({ ...studentForm, guardianName: e.target.value })} /></label><label><span className="mb-1.5 block text-[11px] font-bold text-[#657584]">Telefone</span><input className={fieldClass} placeholder="(00) 00000-0000" value={studentForm.guardianPhone} onChange={e => setStudentForm({ ...studentForm, guardianPhone: e.target.value })} /></label><div className="flex justify-end gap-2 sm:col-span-2"><button type="button" onClick={() => setShowStudentForm(false)} className="rounded-xl px-4 py-2.5 text-xs font-bold text-[#7d8b96] hover:bg-[#f5f7f6]">Cancelar</button><button disabled={addStudent.isPending} className="rounded-xl bg-[#14877e] px-4 py-2.5 text-xs font-bold text-white disabled:opacity-50">{addStudent.isPending ? "Salvando..." : "Salvar aluno"}</button></div></form></CardContent></Card>}
      {showEnrollmentForm && <Card className="border-0 bg-white shadow-[0_7px_25px_rgba(26,54,73,.05)]"><CardContent className="p-5"><div className="mb-5 flex items-center justify-between"><div><h3 className="text-sm font-bold text-[#253b55]">Registrar matrícula</h3><p className="mt-1 text-[11px] text-[#9aa5ae]">Vincule o estudante à turma do ano letivo.</p></div><GraduationCap className="h-5 w-5 text-[#4268aa]" /></div><form onSubmit={submitEnrollment} className="grid gap-3 sm:grid-cols-2"><label className="sm:col-span-2"><span className="mb-1.5 block text-[11px] font-bold text-[#657584]">Aluno *</span><select className={fieldClass} value={enrollmentForm.studentId} onChange={e => setEnrollmentForm({ ...enrollmentForm, studentId: e.target.value })}><option value="">Selecione um aluno</option>{students.data?.map(student => <option key={student.id} value={student.id}>{student.name} · {student.grade}</option>)}</select></label><label><span className="mb-1.5 block text-[11px] font-bold text-[#657584]">Ano letivo *</span><input className={fieldClass} value={enrollmentForm.schoolYear} onChange={e => setEnrollmentForm({ ...enrollmentForm, schoolYear: e.target.value })} /></label><label><span className="mb-1.5 block text-[11px] font-bold text-[#657584]">Turma *</span><input className={fieldClass} placeholder="Ex.: 5º ano A" value={enrollmentForm.className} onChange={e => setEnrollmentForm({ ...enrollmentForm, className: e.target.value })} /></label><label><span className="mb-1.5 block text-[11px] font-bold text-[#657584]">Turno</span><select className={fieldClass} value={enrollmentForm.shift} onChange={e => setEnrollmentForm({ ...enrollmentForm, shift: e.target.value as typeof enrollmentForm.shift })}><option value="morning">Manhã</option><option value="afternoon">Tarde</option><option value="fulltime">Integral</option></select></label><div className="flex justify-end gap-2 sm:col-span-2"><button type="button" onClick={() => setShowEnrollmentForm(false)} className="rounded-xl px-4 py-2.5 text-xs font-bold text-[#7d8b96] hover:bg-[#f5f7f6]">Cancelar</button><button disabled={addEnrollment.isPending} className="rounded-xl bg-[#4268aa] px-4 py-2.5 text-xs font-bold text-white disabled:opacity-50">{addEnrollment.isPending ? "Salvando..." : "Salvar matrícula"}</button></div></form></CardContent></Card>}
    </section>}
    <section className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]">
      <Card className="border-0 bg-white shadow-[0_7px_25px_rgba(26,54,73,.05)]"><CardContent className="p-0"><div className="flex flex-col justify-between gap-3 border-b border-[#edf0ef] px-5 py-5 sm:flex-row sm:items-center"><div><h3 className="text-sm font-bold text-[#253b55]">Estudantes cadastrados</h3><p className="mt-1 text-[11px] text-[#9aa5ae]">{filtered.length} aluno(s) encontrado(s)</p></div><div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-[#a7b2b9]" /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Buscar aluno..." className="h-9 w-full rounded-lg border border-[#e4eae8] bg-[#fbfcfb] pl-9 pr-3 text-xs outline-none focus:border-[#76c9bc] sm:w-52" /></div></div><div className="divide-y divide-[#f0f2f1]">{students.isLoading ? <div className="p-8 text-center text-sm text-[#9aa5ae]">Carregando alunos...</div> : filtered.length ? filtered.map(student => <div key={student.id} className="flex items-center gap-3 px-5 py-4"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-[#e8f3f1] text-xs font-bold text-[#14877e]">{student.name.split(" ").map(part => part[0]).slice(0, 2).join("")}</div><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold text-[#3b4d60]">{student.name}</p><p className="mt-1 truncate text-[11px] text-[#8d99a3]">{student.grade} · responsável: {student.guardianName}</p></div><div className="hidden items-center gap-1 text-[10px] text-[#8d99a3] sm:flex"><Phone className="h-3 w-3" />{student.guardianPhone || "Sem telefone"}</div><Badge className="border-0 bg-[#e7f4f1] text-[9px] font-bold text-[#14877e]">Ativo</Badge></div>) : <div className="p-8 text-center text-sm text-[#9aa5ae]">Nenhum aluno encontrado.</div>}</div></CardContent></Card>
      <Card className="border-0 bg-white shadow-[0_7px_25px_rgba(26,54,73,.05)]"><CardContent className="p-0"><div className="border-b border-[#edf0ef] px-5 py-5"><h3 className="text-sm font-bold text-[#253b55]">Matrículas recentes</h3><p className="mt-1 text-[11px] text-[#9aa5ae]">Vínculos ativos com o ano letivo</p></div><div className="divide-y divide-[#f0f2f1]">{enrollments.data?.length ? enrollments.data.slice(0, 8).map(enrollment => <div key={enrollment.id} className="flex items-center gap-3 px-5 py-4"><div className="grid h-8 w-8 place-items-center rounded-lg bg-[#edf1f9] text-[#5470aa]"><GraduationCap className="h-4 w-4" /></div><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold text-[#3b4d60]">{enrollment.studentName ?? "Aluno"}</p><p className="mt-1 text-[10px] text-[#8d99a3]">{enrollment.className} · {enrollment.shift === "morning" ? "Manhã" : enrollment.shift === "afternoon" ? "Tarde" : "Integral"}</p></div><Badge variant="outline" className="border-[#d9e6f6] bg-[#f6f8fd] text-[9px] font-bold text-[#5470aa]">{enrollment.schoolYear}</Badge></div>) : <div className="p-8 text-center text-sm text-[#9aa5ae]">Ainda não há matrículas.</div>}</div></CardContent></Card>
    </section>
  </div>;
}
