import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { permissionKeys, permissionLabels, type PermissionKey } from "@/../../shared/permissions";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Eye, EyeOff, KeyRound, LockKeyhole, Pencil, Plus, ShieldCheck, UserRoundCheck, UserRoundX, UsersRound } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const initial = { fullName: "", cpfFirstFour: "", roleId: "", password: "" };
const emptyRole = { id: null as number | null, name: "", permissions: [] as PermissionKey[] };
function errorMessage(error: unknown) { return error instanceof Error ? error.message : "Não foi possível concluir a operação."; }
function parsePermissions(value: string): PermissionKey[] { try { const parsed = JSON.parse(value); return Array.isArray(parsed) ? parsed.filter((item): item is PermissionKey => permissionKeys.includes(item)) : []; } catch { return []; } }

export default function TeamAccess() {
  const { user } = useAuth();
  const owner = user?.localRole === "owner";
  const [form, setForm] = useState(initial);
  const [roleForm, setRoleForm] = useState(emptyRole);
  const [showPassword, setShowPassword] = useState(false);
  const [toggleTarget, setToggleTarget] = useState<{ id: number; name: string; active: boolean } | null>(null);
  const [resetTarget, setResetTarget] = useState<{ id: number; name: string } | null>(null);
  const [ownerPassword, setOwnerPassword] = useState("");
  const [newPassword, setNewPassword] = useState("");
  const utils = trpc.useUtils();
  const team = trpc.staff.list.useQuery(undefined, { enabled: owner, retry: false });
  const roles = trpc.staff.roles.useQuery(undefined, { enabled: owner, retry: false });
  const create = trpc.staff.create.useMutation({ onSuccess: async username => { setForm(initial); await utils.staff.list.invalidate(); toast.success(`Funcionário cadastrado: ${username}`); }, onError: error => toast.error(error.message) });
  const createRole = trpc.staff.createRole.useMutation({ onSuccess: async role => { setRoleForm({ id: role?.id ?? null, name: role?.name ?? "", permissions: role ? parsePermissions(role.permissions) : [] }); await utils.staff.roles.invalidate(); toast.success("Função criada com sucesso."); }, onError: error => toast.error(error.message) });
  const updateRole = trpc.staff.updateRole.useMutation({ onSuccess: async () => { await utils.staff.roles.invalidate(); setRoleForm(emptyRole); toast.success("Permissões atualizadas."); }, onError: error => toast.error(error.message) });
  const setActive = trpc.staff.setActive.useMutation({ onSuccess: async () => { setToggleTarget(null); await utils.staff.list.invalidate(); toast.success("Acesso atualizado. Sessões anteriores foram encerradas."); }, onError: error => toast.error(error.message) });
  const reset = trpc.staff.resetPassword.useMutation({ onSuccess: () => { setResetTarget(null); setOwnerPassword(""); setNewPassword(""); toast.success("Senha alterada. O funcionário precisará entrar novamente."); }, onError: error => toast.error(error.message) });
  const firstName = form.fullName.trim().split(/\s+/)[0] ?? "";
  const preview = firstName.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z]/g, "") + form.cpfFirstFour;
  const togglePermission = (permission: PermissionKey) => setRoleForm(current => ({ ...current, permissions: current.permissions.includes(permission) ? current.permissions.filter(item => item !== permission) : [...current.permissions, permission] }));

  if (!owner) return <Card><CardContent className="p-8 text-sm text-[#516273]">Esta área é exclusiva do dono do colégio.</CardContent></Card>;
  return <div className="mx-auto max-w-7xl space-y-7">
    <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#138378]">Administração geral</p><h2 className="mt-2 font-display text-3xl font-bold text-[#12233f]">Equipe e acessos</h2><p className="mt-2 text-sm text-[#758492]">Crie funções como Secretaria ou Administrador e escolha exatamente quais módulos cada uma pode acessar.</p></div><Badge className="w-fit bg-[#e5f3ef] px-3 py-1.5 text-[#10766c] hover:bg-[#e5f3ef]"><ShieldCheck className="mr-1.5 h-4 w-4" /> Exclusivo do dono</Badge></div>
    <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_380px]">
      <Card className="border-[#e6eae9] bg-white shadow-[0_12px_32px_rgba(26,54,73,.055)]"><CardContent className="p-5 sm:p-7"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#e7f4f1] text-[#14877e]"><UsersRound className="h-5 w-5" /></div><div><h3 className="font-bold text-[#12233f]">Pessoas cadastradas</h3><p className="text-xs text-[#647b79]">A função controla os módulos disponíveis para cada funcionário.</p></div></div>{team.isLoading && <p className="mt-7 text-sm text-[#647b79]">Carregando equipe...</p>}{team.isError && <p role="alert" className="mt-7 text-sm text-red-700">{errorMessage(team.error)}</p>}<div className="mt-5 space-y-3">{team.data?.map(person => <div key={person.id} className="rounded-2xl border border-[#e8edeb] p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div className="flex items-start gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-[#f1e7de] text-sm font-bold text-[#9f6549]">{person.fullName.charAt(0).toUpperCase()}</div><div><p className="font-semibold text-[#12233f]">{person.fullName}</p><p className="mt-0.5 text-xs text-[#647b79]">{person.roleName ?? person.jobTitle} · <span className="font-mono">{person.username}</span></p></div></div><Badge variant="outline" className={person.active ? "border-[#ccece1] bg-[#eff9f4] text-[#158265]" : "border-[#e5e7e9] bg-[#f6f6f6] text-[#7b8390]"}>{person.active ? "Ativo" : "Sem acesso"}</Badge></div>{person.role === "staff" ? <div className="mt-4 grid gap-2 border-t border-[#edf0ef] pt-4 sm:flex sm:flex-wrap"><Button variant="outline" size="sm" onClick={() => setResetTarget({ id: person.id, name: person.fullName })}><KeyRound className="mr-2 h-4 w-4" />Trocar senha</Button><Button variant="outline" size="sm" className={person.active ? "text-[#ad5b4d]" : "text-[#13766d]"} onClick={() => setToggleTarget({ id: person.id, name: person.fullName, active: Boolean(person.active) })}>{person.active ? <UserRoundX className="mr-2 h-4 w-4" /> : <UserRoundCheck className="mr-2 h-4 w-4" />}{person.active ? "Remover acesso" : "Reativar acesso"}</Button></div> : <p className="mt-3 text-xs text-[#647b79]">O dono sempre possui acesso total e não pode ser removido por este painel.</p>}</div>)}</div></CardContent></Card>
      <Card className="h-fit border-[#e6eae9] bg-[#fffefb] shadow-[0_12px_32px_rgba(26,54,73,.055)]"><CardContent className="p-5 sm:p-6"><div className="flex items-center gap-2"><Plus className="h-5 w-5 text-[#14877e]" /><h3 className="font-bold text-[#12233f]">Adicionar funcionário</h3></div><p className="mt-2 text-xs leading-5 text-[#647b79]">Escolha uma função existente. O login combina o primeiro nome com os quatro primeiros dígitos informados do CPF.</p><form className="mt-5 space-y-4" onSubmit={event => { event.preventDefault(); if (!form.roleId) return toast.error("Selecione uma função."); create.mutate({ ...form, firstName, roleId: Number(form.roleId) }); }}><div className="space-y-1.5"><Label htmlFor="team-name">Nome completo</Label><Input id="team-name" autoComplete="name" required minLength={2} maxLength={160} placeholder="Amanda Silva" value={form.fullName} onChange={event => setForm({ ...form, fullName: event.target.value })} /></div><div className="space-y-1.5"><Label htmlFor="team-role">Função</Label><select id="team-role" required className="h-11 w-full rounded-xl border border-[#cfddd6] bg-[#fbfcf9] px-3.5 text-sm text-[#3b4d60]" value={form.roleId} onChange={event => setForm({ ...form, roleId: event.target.value })}><option value="">Selecione uma função</option>{roles.data?.map(role => <option key={role.id} value={role.id}>{role.name}</option>)}</select></div><div className="space-y-1.5"><Label htmlFor="team-digits">Quatro primeiros dígitos do CPF</Label><Input id="team-digits" required inputMode="numeric" pattern="[0-9]{4}" maxLength={4} placeholder="1234" value={form.cpfFirstFour} onChange={event => setForm({ ...form, cpfFirstFour: event.target.value.replace(/\D/g, "").slice(0, 4) })} /></div><div className="rounded-xl bg-[#eef5f3] px-3 py-2 text-xs text-[#486e69]">Login: <strong className="font-mono">{preview || "nome1234"}</strong></div><div className="space-y-1.5"><Label htmlFor="team-password">Senha inicial</Label><div className="relative"><Input id="team-password" type={showPassword ? "text" : "password"} autoComplete="new-password" required minLength={15} maxLength={128} placeholder="Mínimo de 15 caracteres" className="pr-10" value={form.password} onChange={event => setForm({ ...form, password: event.target.value })} /><button type="button" className="absolute inset-y-0 right-2 px-2 text-[#7b8b98]" aria-label={showPassword ? "Ocultar senha" : "Mostrar senha"} onClick={() => setShowPassword(!showPassword)}>{showPassword ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}</button></div></div><Button disabled={create.isPending || !roles.data?.length} className="w-full bg-[#12233f] text-white hover:bg-[#244165]">{create.isPending ? "Salvando..." : "Criar acesso"}</Button></form></CardContent></Card>
    </div>
    <Card className="border-[#e6eae9] bg-white shadow-[0_12px_32px_rgba(26,54,73,.055)]"><CardContent className="p-5 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><h3 className="font-bold text-[#12233f]">Funções e permissões</h3><p className="mt-1 text-xs text-[#647b79]">Cada função pode liberar um ou mais módulos. Alterações valem para o próximo acesso ao módulo.</p></div><Button variant="outline" onClick={() => setRoleForm(emptyRole)}><Plus className="mr-2 h-4 w-4" />Nova função</Button></div><div className="mt-5 grid gap-4 lg:grid-cols-[280px_minmax(0,1fr)]"><div className="space-y-2">{roles.data?.map(role => <button type="button" key={role.id} onClick={() => setRoleForm({ id: role.id, name: role.name, permissions: parsePermissions(role.permissions) })} className={`flex w-full items-center justify-between rounded-xl border px-3 py-3 text-left text-sm ${roleForm.id === role.id ? "border-[#83cfc0] bg-[#eef8f4] text-[#155a52]" : "border-[#e8edeb] text-[#3b4d60] hover:bg-[#fbfdfb]"}`}><span className="font-semibold">{role.name}</span><Pencil className="h-3.5 w-3.5" /></button>)}{!roles.data?.length && <p className="rounded-xl bg-[#fff5eb] p-3 text-xs text-[#8d6438]">Crie a primeira função para liberar acessos.</p>}</div><form className="rounded-2xl border border-[#edf0ef] bg-[#fbfcfb] p-4" onSubmit={event => { event.preventDefault(); if (roleForm.id) updateRole.mutate({ id: roleForm.id, name: roleForm.name, permissions: roleForm.permissions }); else createRole.mutate({ name: roleForm.name, permissions: roleForm.permissions }); }}><Label htmlFor="role-name">Nome da função</Label><Input id="role-name" required minLength={2} maxLength={80} className="mt-1.5 max-w-md" placeholder="Ex.: Secretaria" value={roleForm.name} onChange={event => setRoleForm({ ...roleForm, name: event.target.value })} /><p className="mt-4 text-xs font-bold uppercase tracking-[.12em] text-[#647b79]">Módulos liberados</p><div className="mt-2 grid gap-2 sm:grid-cols-2">{permissionKeys.map(permission => <label key={permission} className="flex cursor-pointer items-center gap-2 rounded-xl border border-[#e6edeb] bg-white px-3 py-3 text-sm text-[#3b4d60]"><input type="checkbox" checked={roleForm.permissions.includes(permission)} onChange={() => togglePermission(permission)} />{permissionLabels[permission]}</label>)}</div><Button disabled={createRole.isPending || updateRole.isPending} className="mt-4 bg-[#14877e] text-white hover:bg-[#0f6e65]">{roleForm.id ? "Salvar alterações" : "Criar função"}</Button></form></div></CardContent></Card>
    <div className="flex items-start gap-3 rounded-xl bg-[#eef5f3] p-4 text-xs leading-5 text-[#486e69]"><LockKeyhole className="mt-0.5 h-4 w-4 shrink-0" /><p>O dono sempre mantém acesso total. O funcionário só consegue consultar ou alterar os módulos liberados pela função, mesmo que tente abrir outra rota diretamente.</p></div>
    <Dialog open={Boolean(toggleTarget)} onOpenChange={open => { if (!open) setToggleTarget(null); }}><DialogContent><DialogHeader><DialogTitle>{toggleTarget?.active ? "Remover acesso" : "Reativar acesso"}</DialogTitle><DialogDescription>{toggleTarget?.active ? `A conta de ${toggleTarget.name} será bloqueada e as sessões serão encerradas. O histórico de ações não será apagado.` : `A conta de ${toggleTarget?.name} voltará a poder entrar com a senha atual.`}</DialogDescription></DialogHeader><div className="flex justify-end gap-2"><Button variant="outline" onClick={() => setToggleTarget(null)}>Voltar</Button><Button disabled={setActive.isPending} className="bg-[#12233f] text-white" onClick={() => { if (toggleTarget) setActive.mutate({ id: toggleTarget.id, active: !toggleTarget.active }); }}>Confirmar</Button></div></DialogContent></Dialog>
    <Dialog open={Boolean(resetTarget)} onOpenChange={open => { if (!open) { setResetTarget(null); setOwnerPassword(""); setNewPassword(""); } }}><DialogContent><DialogHeader><DialogTitle>Trocar senha de {resetTarget?.name}</DialogTitle><DialogDescription>Confirme com sua própria senha. A sessão atual do funcionário será encerrada.</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={event => { event.preventDefault(); if (resetTarget) reset.mutate({ targetId: resetTarget.id, ownerPassword, newPassword }); }}><div className="space-y-1.5"><Label htmlFor="owner-password">Sua senha de dono</Label><Input id="owner-password" type="password" autoComplete="current-password" required value={ownerPassword} onChange={event => setOwnerPassword(event.target.value)} /></div><div className="space-y-1.5"><Label htmlFor="new-staff-password">Nova senha do funcionário</Label><Input id="new-staff-password" type="password" autoComplete="new-password" required minLength={15} maxLength={128} placeholder="Mínimo de 15 caracteres" value={newPassword} onChange={event => setNewPassword(event.target.value)} /></div><Button disabled={reset.isPending} className="w-full bg-[#12233f] text-white">{reset.isPending ? "Atualizando..." : "Salvar nova senha"}</Button></form></DialogContent></Dialog>
  </div>;
}
